POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Yann Bonzom",
    "number": "438-389-9209"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "438-389-9209"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "438-389-9209"
}

